# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: enabled
dist: trusty
cache:
  - packages
  - ccache
latex: false

matrix:
    include:
        - os: osx
          r: 3.4
          before_install: ''
          disable_homebrew: true
          env:
           - BUILD_NAME=osx_release
           - R_CODECOV=true
        - os: osx
          r: oldrel
          before_install: ''
          disable_homebrew: true
          env:
           - BUILD_NAME=osx_oldrel
           - R_CODECOV=false



